/**
 * @file Category icon resolution (PRD §5, decision V2-8). Pure — no DOM, no
 * fetch — so the resolution order is unit-testable without a browser. The
 * caller supplies the manifest (public/icons/manifest.json, regenerated by
 * scripts/build-icon-manifest.mjs) and renders whatever this returns.
 *
 * RESOLUTION ORDER, highest priority first:
 *   1. `<category-slug>.png` in the manifest — the PRD §5 convention. An icon
 *      named for its category always wins, so dropping `marvel.png` into
 *      public/icons/ is all it takes to give Marvel an icon.
 *   2. The category's `Icon:` frontmatter stem (questions.js `category.icon`),
 *      e.g. `Icon: Icon_Lightning` -> `Icon_Lightning.png`. This is how the
 *      18 legacy symbol PNGs (Icon_Basketball, Icon_MovieCam, …) get attached
 *      to categories whose slugs they don't match. Ignored when the named file
 *      isn't in the manifest, so a stale frontmatter line degrades to (3)
 *      rather than rendering a broken image.
 *   3. Numbered circle — the V2-8 fallback: a circle containing the category's
 *      1-based position on the board (1–10). Never a broken image, never an
 *      empty tile.
 *
 * WHY A MANIFEST INSTEAD OF PROBING: the alternative is requesting
 * `/icons/<slug>.png` and treating a 404 as "absent", which costs one failed
 * request per iconless tile on every board render and paints a broken image
 * first. The manifest makes absence knowable before the first paint.
 */

/** Directory the icons are served from (public/icons -> /icons at runtime). */
export const ICON_BASE = '/icons';

/**
 * @typedef {Object} IconImage
 * @property {'image'} kind
 * @property {string} src - URL to render in an <img>.
 * @property {'slug'|'frontmatter'} via - which rule matched (diagnostics/tests).
 */

/**
 * @typedef {Object} IconNumber
 * @property {'number'} kind
 * @property {number} n - 1-based board position to draw inside the circle.
 * @property {'fallback'} via
 */

/** @typedef {IconImage|IconNumber} IconResolution */

/**
 * Index a manifest for O(1) lookup. Accepts filenames with or without the
 * `.png` extension; comparison is case-insensitive because the legacy files
 * are PascalCase (`Icon_Lightning.png`) while slugs are kebab-case.
 * @param {string[]} manifest - e.g. ["Icon_Lightning.png", "marvel.png"]
 * @returns {Map<string, string>} lowercased stem -> real filename
 */
export function indexManifest(manifest) {
  const byStem = new Map();
  for (const file of manifest || []) {
    if (typeof file !== 'string') continue;
    const stem = file.replace(/\.png$/i, '');
    byStem.set(stem.toLowerCase(), file);
  }
  return byStem;
}

/**
 * Resolve one category's icon.
 * @param {{slug: string, icon?: ?string}} category - as produced by
 *   `questions.parseCategory`; `icon` is the `Icon:` frontmatter stem or null.
 * @param {number} index - 0-based position of this category on the board; the
 *   numbered-circle fallback renders `index + 1`.
 * @param {Object} opts
 * @param {Map<string, string>|string[]} opts.manifest - `indexManifest` result,
 *   or a raw filename array (indexed on the fly).
 * @param {string} [opts.base=ICON_BASE]
 * @returns {IconResolution}
 */
export function resolveIcon(category, index, { manifest, base = ICON_BASE }) {
  const byStem = manifest instanceof Map ? manifest : indexManifest(manifest);
  const url = (file) => `${base}/${file}`;

  const bySlug = category && category.slug ? byStem.get(String(category.slug).toLowerCase()) : undefined;
  if (bySlug) return { kind: 'image', src: url(bySlug), via: 'slug' };

  if (category && category.icon) {
    const stem = String(category.icon).replace(/\.png$/i, '').toLowerCase();
    const byFrontmatter = byStem.get(stem);
    if (byFrontmatter) return { kind: 'image', src: url(byFrontmatter), via: 'frontmatter' };
  }

  return { kind: 'number', n: index + 1, via: 'fallback' };
}

/**
 * Resolve a whole board's worth of categories in one pass, so the numbered
 * fallbacks come out 1..n in board order.
 * @param {Array<{slug: string, icon?: ?string}>} categories
 * @param {Object} opts - same as `resolveIcon`.
 * @returns {IconResolution[]}
 */
export function resolveIcons(categories, opts) {
  const manifest = opts.manifest instanceof Map ? opts.manifest : indexManifest(opts.manifest);
  return categories.map((cat, i) => resolveIcon(cat, i, { ...opts, manifest }));
}

/**
 * Fetch the manifest that ships beside the icons. Returns an empty index (all
 * categories fall back to numbered circles) if it can't be read, rather than
 * failing a board render over a missing static file.
 * @param {string} [base=ICON_BASE]
 * @returns {Promise<Map<string, string>>}
 */
export async function loadIconManifest(base = ICON_BASE) {
  try {
    const res = await fetch(`${base}/manifest.json`);
    if (!res.ok) return new Map();
    const files = await res.json();
    return indexManifest(Array.isArray(files) ? files : []);
  } catch {
    return new Map();
  }
}
